# Generated by Django 4.1.3 on 2022-11-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('das_menu', '0004_alter_menuitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='stock',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
